blueprint:
  name: LPB - Check the occupancy in other rooms
  description: '
  
  This blueprint checks the occupancy in other rooms. If no occupancy is detected then this room is occupied.

  '
  domain: automation
  input:
    area_state:
      name: Area state
      description: 'Input select that handles the area state.'
      selector:
        entity:
          domain: input_select
mode: restart
trigger:
  - platform: state
    entity_id: !input "area_state"
    to:
      - Checking occupancy
      - Not occupied and open
action:
  # Query the rest of rooms
  - wait_for_trigger:
      - platform: event
        event_type: less_push_buttons
        event_data:
          lpb_type: notify
          occupied: true
    timeout: "00:00:10"
    # If no response then the room is still occupied
  - choose:
      - conditions: "{{ wait.completed }}"
        sequence:
          - event: less_push_buttons
            event_data:
              lpb_type: notify_house
              occupied: true
              target_entity_id: !input "area_state"
              origin_entity_id: !input "area_state"
              origin_state: External
      - conditions: "{{ not wait.completed }}"
        sequence:
          - event: less_push_buttons
            event_data:
              lpb_type: notify_house
              occupied: false
              target_entity_id: !input "area_state"
              origin_entity_id: !input "area_state"
              origin_state: External