blueprint:
  name: LPB - Lights management only turn off
  description: Turn lights off not on.
  domain: automation
  input:
    target_light:
      name: Lights
      description: The lights to keep in sync.
      selector:
        entity:
          domain: light
    area_state:
      name: Area state
      selector:
        entity:
          domain: input_select
mode: parallel
trigger:
  - platform: state
    entity_id: !input "area_state"
action:
  - variables:
      area_input_select: !input "area_state"
  - choose:
      # Turn off the lights
      - conditions:
          - "{{ is_state(area_input_select, 'Not occupied and closed')
            or is_state(area_input_select, 'Not occupied and open')
            or is_state(area_input_select, 'Not occupied') }}"
        sequence:
          - service: light.turn_off
            entity_id: !input target_light
