blueprint:
  name: LPB - Reference lights
  description: XXXXX Turn lights on and off with iluminance, brightness and diferents temperature of color depending of the sun (day/night).
  domain: automation
  input:
    area_state:
      name: Area state
      selector:
        entity:
          domain: input_select
    light_state:
      name: Light state
      selector:
        entity:
          domain: input_select
mode: parallel
max_exceeded: silent
trigger:
  - platform: state
    entity_id: !input "area_state"
  - platform: state
    entity_id: !input "light_state"
action:
  - variables:
      area_input_select: !input "area_state"
      light_input_select: !input "light_state"
      area_occupied: "{{ is_state(area_input_select, 'Checking entry')
        or is_state(area_input_select, 'Occupied')
        or is_state(area_input_select, 'Occupied and closed')
        or is_state(area_input_select, 'Occupied and open')
        or is_state(area_input_select, 'Checking occupancy')
        or is_state(area_input_select, 'Checking occupancy by closure')
        or is_state(area_input_select, 'Checking occupancy by opening') }}"
      light_off:
        "{{ is_state(light_input_select, 'Light off with insufficient lighting')
        or is_state(light_input_select, 'Requested light off with insufficient lighting') }}"
  - choose:
      - conditions:
          - "{{ area_occupied and light_off }}"
        sequence:
          - event: less_push_buttons
            event_data:
              lpb_type: request
              requested: reference_light
              target_entity_id: !input "light_state"
      - conditions:
          - "{{ not area_occupied and is_state(light_input_select, 'Reference light') }}"
        sequence:
          - event: less_push_buttons
            event_data:
              lpb_type: request
              requested: turn_off_light
              target_entity_id: !input "light_state"
