blueprint:
  name: LPB - Check the occupancy in other rooms
  description: '
  
  This blueprint checks the occupancy in other rooms. If no occupancy is detected then this room is occupied.

  '
  domain: automation
  input:
    area_state:
      name: Area state
      description: 'Input select that handles the area state.'
      selector:
        entity:
          domain: input_select
mode: parallel
trigger:
  - platform: event
    event_type: less_push_buttons
    event_data:
      lpb_type: notify
      occupied: true
condition:
  - condition: state
    entity_id: !input "area_state"
    state:
      - Checking occupancy
      - Not occupied and open
action:
  - event: less_push_buttons
    event_data:
      lpb_type: notify
      occupied: true
      target_entity_id: !input "area_state"
      origin_entity_id: !input "area_state"
      origin_state: External