blueprint:
  name: LPB - Scene sync
  description: Descripcion
  domain: automation
  input:
    scene_state:
      name: Scene state
      description: Input select that handles the scene state.
      selector:
        entity:
          domain: input_select
mode: parallel
trigger:
  - platform: state
    entity_id: !input "scene_state"
action:
  - variables:
      scene_select: !input "scene_state"
      scene_to_call: "{{ states(scene_select) }}"
  - service: scene.turn_on
    target:
      entity_id: "{{ scene_to_call }}"
