blueprint:
  name: LPB - Switch management with time range and workdays
  description: XXXX Turn lights on and off with brightness depending of the sun (day/night).
  domain: automation
  input:
    target_switch:
      name: Lights
      description: The lights to keep in sync.
      selector:
        entity:
          domain: switch
    area_state:
      name: Area state
      selector:
        entity:
          domain: input_select
    start_time:
      name: Start time
      description: XXXXX Brightness of the light when turning on in the day, the sun is 'above_horizon'.
      selector:
        time:
    end_time:
      name: End time
      description: XXXXX Brightness of the light when turning on in the day, the sun is 'above_horizon'.
      selector:
        time:
    workday_sensor:
      name: Workday workday_sensor
      description: Workday workday_sensor
      selector:
        entity:
          domain: binary_sensor
mode: parallel
trigger:
  - platform: state
    entity_id: !input "area_state"
condition:
  - condition: time
    after: !input "start_time"
    before: !input "end_time"
action:
  - variables:
      area_input_select: !input "area_state"
  - choose:
      # Turn off the lights
      - conditions:
          - condition: state
            entity_id: !input "area_state"
            state:
              - Not occupied and closed
              - Not occupied and open
              - Not occupied
        sequence:
          - service: switch.turn_off
            entity_id: !input "target_switch"
    default:
      - service: switch.turn_on
        entity_id: !input "target_switch"
