blueprint:
  name: LPB - Dev - State of house occupancy controlled by a door sensor
  description: 'This blueprint controls the occupancy of the house using one door sensor, usually the front door of the house.

  The state of the house is maintained in an input select, that must exists, with the following items:
      - Occupied
      - Not occupied
      - Checking occupancy

  To check if the house is occupied it uses the rest of the Less Push Buttons ecosystem of automations.
  '
  domain: automation
  input:
    door_sensor:
      name: Door Sensor
      description: The door sensor of the entrance door to the house.
      selector:
        entity:
          domain: binary_sensor
          device_class: opening
    area_state:
      name: House state
      description: 'Input select that handles the area state. It must have the following items:
      - Occupied
      - Not occupied
      - Checking occupancy
      '
      selector:
        entity:
          domain: input_select
    checking_occupancy_wait:
      name: Checking occupancy timeout
      description: Seconds to check if occupancy is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
mode: parallel
max_exceeded: silent
trigger:
  - platform: state
    entity_id: !input "door_sensor"
    to: 'off'
action:
  - variables:
      door_entity_id: !input "door_sensor"
      door_change: "{{ trigger.entity_id == door_entity_id }}"
  - choose:
# Events and next state
      - conditions:
          - "{{ door_change }}"
        sequence:
          - service: input_select.select_option
            data:
              entity_id: !input "area_state"
              option: Checking occupancy
# Timeouts
      - conditions:
          - condition: state
            entity_id: !input "area_state"
            state: Checking occupancy
        sequence: 
          # Query the rooms of the house
          - event: less_push_buttons
            event_data:
              lpb_type: query
              query_state: Occupied
              origin_entity_id: !input "area_state"
          - wait_for_trigger:
              - platform: event
                event_type: less_push_buttons
                event_data:
                  lpb_type: response
                  occupied: true
                  target_entity_id: !input "area_state"
            timeout: "00:00:05"
            # If no response then the house is still occupied
          - choose:
              - conditions: "{{ not wait.completed }}"
                sequence:
                  - service: input_select.select_option
                    data:
                      entity_id: !input "area_state"
                      option: Occupied
            default:
              - service: input_select.select_option
                data:
                  entity_id: !input "area_state"
                  option: Not occupied              
