- alias: Gestion de Aseo
  mode: parallel
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_9cb7ce03_on_off
  - platform: event
    event_type: evento_cambio_modo_aseo
  - platform: state
    entity_id: input_select.modo_aseo
  action:
  - variables:
      door_open: '{{ trigger.entity_id == ''binary_sensor.lumi_lumi_sensor_magnet_aq2_9cb7ce03_on_off'' and trigger.to_state.state == ''on'' }}'
      door_closed: '{{ trigger.entity_id == ''binary_sensor.lumi_lumi_sensor_magnet_aq2_9cb7ce03_on_off'' and trigger.to_state.state == ''off'' }}'
  - choose:
    - conditions: 
      - '{{ door_open }}'
      - '{{ is_state(''input_select.modo_aseo'', ''Vacio y cerrada'') }}'
      sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.modo_aseo
          option: Posible entrada
    - conditions: 
      - '{{ door_open }}'
      - '{{ is_state(''input_select.modo_aseo'', ''Ocupado y cerrada'') }}'
      sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.modo_aseo
          option: Posible salida 2
    - conditions: 
      - '{{ door_closed }}'
      - '{{ is_state(''input_select.modo_aseo'', ''Posible entrada'') }}'
      sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.modo_aseo
          option: Vacio y cerrada
    - conditions: 
      - '{{ door_closed }}'
      - '{{ is_state(''input_select.modo_aseo'', ''Vacio y abierta'') }}'        
      sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.modo_aseo
          option: Vacio y cerrada
    - conditions: 
      - '{{ door_closed }}'
      - '{{ is_state(''input_select.modo_aseo'', ''Ocupado y abierta'') }}'            
      sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.modo_aseo
          option: Posible salida 1
    - conditions: 
      - '{{ door_closed }}'
      - '{{ is_state(''input_select.modo_aseo'', ''Posible salida 2'') }}'        
      sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.modo_aseo
          option: Vacio y cerrada
    - conditions: 
      - '{{ trigger.event.data.ocupado == true }}'
      - '{{ is_state(''input_select.modo_aseo'', ''Vacio y cerrada'') or is_state(''input_select.modo_aseo'', ''Posible salida 1'') }}'           
      - '{{ is_state(''input_select.modo_aseo'', trigger.event.data.origin_state) and trigger.event.data.origin_entity_id == ''input_select.modo_aseo'' }}'      
      sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.modo_aseo
          option: Ocupado y cerrada
    - conditions: 
      - '{{ trigger.event.data.ocupado == true }}'
      - '{{ is_state(''input_select.modo_aseo'', ''Posible entrada'') or is_state(''input_select.modo_aseo'', ''Vacio y abierta'') or is_state(''input_select.modo_aseo'', ''Ocupado y abierta'') or is_state(''input_select.modo_aseo'', ''Posible salida 2'') }}'
      - '{{ is_state(''input_select.modo_aseo'', trigger.event.data.origin_state) and trigger.event.data.origin_entity_id == ''input_select.modo_aseo'' }}'      
      sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.modo_aseo
          option: Ocupado y abierta
    - conditions: 
      - '{{ trigger.event.data.ocupado == false }}'
      - '{{ is_state(''input_select.modo_aseo'', ''Posible entrada'') or is_state(''input_select.modo_aseo'', ''Ocupado y abierta'') or is_state(''input_select.modo_aseo'', ''Posible salida 2'') }}'
      - '{{ is_state(''input_select.modo_aseo'', trigger.event.data.origin_state) and trigger.event.data.origin_entity_id == ''input_select.modo_aseo'' }}'
      sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.modo_aseo
          option: Vacio y abierta
    - conditions: 
      - '{{ trigger.event.data.ocupado == false }}'
      - '{{ is_state(''input_select.modo_aseo'', ''Posible salida 1'') }}'
      - '{{ is_state(''input_select.modo_aseo'', trigger.event.data.origin_state) and trigger.event.data.origin_entity_id == ''input_select.modo_aseo'' }}'
      sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.modo_aseo
          option: Vacio y cerrada
    - conditions: 
      - condition: state  
        entity_id: input_select.modo_aseo
        state: Vacio y cerrada
      sequence:
      - service: light.turn_off
        data:
          entity_id: light.luz_aseo_level_light_color_on_off
      - wait_template: '{{ is_state(''binary_sensor.lumi_lumi_sensor_motion_aq2_49738205_ias_zone'', ''on'') }}'
        timeout: 00:00:15
      - choose:
        - conditions:
          - condition: template
            value_template: '{{ not wait.completed }}'
          sequence:
          - event: evento_cambio_modo_aseo
            event_data:
              ocupado: false
              origin_entity_id: input_select.modo_aseo
              origin_state: Vacio y cerrada              
        default:
        - event: evento_cambio_modo_aseo
          event_data:
            ocupado: true
            origin_entity_id: input_select.modo_aseo
            origin_state: Vacio y cerrada            
    - conditions: 
      - condition: state  
        entity_id: input_select.modo_aseo
        state: Posible entrada
      sequence:
      - choose:
        - conditions:
          - condition: state  
            entity_id: sun.sun
            state: 'above_horizon'
          sequence:
          - service: light.turn_on
            data:
              entity_id: light.luz_aseo_level_light_color_on_off
              brightness_pct: 50
              kelvin: 4000
        default:
        - service: light.turn_on
          data:
            entity_id: light.luz_aseo_level_light_color_on_off
            brightness_pct: 50
            kelvin: 2700
      - wait_template: '{{ is_state(''binary_sensor.lumi_lumi_sensor_motion_aq2_49738205_ias_zone'',
          ''on'') }}'
        timeout: 00:00:15
      - choose:
        - conditions:
          - condition: template
            value_template: '{{ not wait.completed }}'
          sequence:
          - event: evento_cambio_modo_aseo
            event_data:
              ocupado: false
              origin_entity_id: input_select.modo_aseo
              origin_state: Posible entrada              
        default:
        - event: evento_cambio_modo_aseo
          event_data:
            ocupado: true
            origin_entity_id: input_select.modo_aseo
            origin_state: Posible entrada            
    - conditions: 
      - condition: state  
        entity_id: input_select.modo_aseo
        state: Vacio y abierta
      sequence:
      - service: light.turn_off
        data:
          entity_id: light.luz_aseo_level_light_color_on_off
      - wait_template: '{{ is_state(''binary_sensor.lumi_lumi_sensor_motion_aq2_49738205_ias_zone'', ''on'') }}'
        timeout: 00:00:15
      - choose:
        - conditions:
          - condition: template
            value_template: '{{ not wait.completed }}'
          sequence:
          - event: evento_cambio_modo_aseo
            event_data:
              ocupado: false
              origin_entity_id: input_select.modo_aseo
              origin_state: Vacio y abierta              
        default:
        - event: evento_cambio_modo_aseo
          event_data:
            ocupado: true
            origin_entity_id: input_select.modo_aseo
            origin_state: Vacio y abierta            
    - conditions: 
      - condition: state  
        entity_id: input_select.modo_aseo
        state: Ocupado y abierta
      sequence:
      - service: light.turn_on
        data:
          entity_id: light.luz_aseo_level_light_color_on_off
      - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.lumi_lumi_sensor_motion_aq2_49738205_ias_zone
          to: 'off'
          for: 00:02:00
        timeout:
          minutes: 00:02:01
      - choose:
        - conditions:
          - condition: template
            value_template: '{{ wait.completed }}'
          sequence:
          - event: evento_cambio_modo_aseo
            event_data:
              ocupado: true
              origin_entity_id: input_select.modo_aseo
              origin_state: Ocupado y abierta              
        default:
        - event: evento_cambio_modo_aseo
          event_data:
            ocupado: false
            origin_entity_id: input_select.modo_aseo
            origin_state: Ocupado y abierta            
    - conditions: 
      - condition: state  
        entity_id: input_select.modo_aseo
        state: Posible salida 1
      sequence:
      - service: light.turn_on
        data:
          entity_id: light.luz_aseo_level_light_color_on_off
      - wait_template: '{{ is_state(''binary_sensor.lumi_lumi_sensor_motion_aq2_49738205_ias_zone'',
          ''on'') }}'
        timeout: 00:00:15
      - choose:
        - conditions:
          - condition: template
            value_template: '{{ not wait.completed }}'
          sequence:
          - event: evento_cambio_modo_aseo
            event_data:
              ocupado: false
              origin_entity_id: input_select.modo_aseo
              origin_state: Posible salida 1
        default:
        - event: evento_cambio_modo_aseo
          event_data:
            ocupado: true
            origin_entity_id: input_select.modo_aseo
            origin_state: Posible salida 1            
    - conditions: 
      - condition: state  
        entity_id: input_select.modo_aseo
        state: Posible salida 2
      sequence:
      - service: light.turn_on
        data:
          entity_id: light.luz_aseo_level_light_color_on_off
      - wait_template: '{{ is_state(''binary_sensor.lumi_lumi_sensor_motion_aq2_49738205_ias_zone'',
          ''on'') }}'
        timeout: 00:00:15
      - choose:
        - conditions:
          - condition: template
            value_template: '{{ not wait.completed }}'
          sequence:
          - event: evento_cambio_modo_aseo
            event_data:
              ocupado: false
              origin_entity_id: input_select.modo_aseo
              origin_state: Posible salida 2
        default:
        - event: evento_cambio_modo_aseo
          event_data:
            ocupado: true
            origin_entity_id: input_select.modo_aseo
            origin_state: Posible salida 2
    - conditions: 
      - condition: state  
        entity_id: input_select.modo_aseo
        state: Ocupado y cerrada
      sequence:
      - service: light.turn_on
        data:
          entity_id: light.luz_aseo_level_light_color_on_off
      - wait_template: '{{ is_state(''binary_sensor.lumi_lumi_sensor_motion_aq2_49738205_ias_zone'',
          ''on'') }}'
        timeout: 00:00:15
      - choose:
        - conditions:
          - condition: template
            value_template: '{{ not wait.completed }}'
          sequence:
          - event: evento_cambio_modo_aseo
            event_data:
              ocupado: false
              origin_entity_id: input_select.modo_aseo
              origin_state: Ocupado y cerrada
        default:
        - event: evento_cambio_modo_aseo
          event_data:
            ocupado: true
            origin_entity_id: input_select.modo_aseo
            origin_state: Ocupado y cerrada