blueprint:
  name: LPB - Only one entrace room actions
  description: Blueprint to react to the Less Push Buttons one entrace state change.
  domain: automation
  input:
    area_state:
      name: One entrance area state
      selector:
        entity:
          domain: input_select
    not_occupied_closed_action:
      name: X 1 Light
      description: The light(s) to control
      default: []
      selector:
        action: {}
    not_occupied_open_action:
      name: X 2 Light
      description: The light(s) to control
      default: []
      selector:
        action: {}
    occupied_closed_action:
      name: X 3 Light
      description: The light(s) to control
      default: []
      selector:
        action: {}
    occupied_open_action:
      name: X 4 Light
      description: The light(s) to control
      default: []
      selector:
        action: {}
    checking_entry_action:
      name: X 5 Light
      description: The light(s) to control
      default: []
      selector:
        action: {}
    checking_occupancy_by_closure_action:
      name: X 6 Light
      description: The light(s) to control
      default: []
      selector:
        action: {}
    checking_occupancy_by_opening_action:
      name: X 7 Light
      description: The light(s) to control
      default: []
      selector:
        action: {}
mode: parallel
trigger:
  - platform: state
    entity_id: !input "area_state"
action:
  - variables:
      area_input_select: !input "area_state"
  - choose:
      - conditions:
          - condition: state
            entity_id: !input "area_state"
            state: Not occupied and closed
        sequence: !input 'not_occupied_closed_action'
      - conditions:
          - condition: state
            entity_id: !input "area_state"
            state: Checking entry
        sequence: !input 'checking_entry_action'
      - conditions:
          - condition: state
            entity_id: !input "area_state"
            state: Not occupied and open
        sequence: !input 'not_occupied_open_action'
      - conditions:
          - condition: state
            entity_id: !input "area_state"
            state: Occupied and closed
        sequence: !input 'occupied_open_action'
      - conditions:
          - condition: state
            entity_id: !input "area_state"
            state: Checking occupancy by closure
        sequence: !input 'checking_occupancy_by_closure_action'
      - conditions:
          - condition: state
            entity_id: !input "area_state"
            state: Checking occupancy by opening
        sequence: !input 'checking_occupancy_by_opening_action'
      - conditions:
          - condition: state
            entity_id: !input "area_state"
            state: Occupied and closed
        sequence: !input 'occupied_closed_action'
