blueprint:
  name: LPB - Only one entrace room actions
  description: XXXXTurn light on based on detected motion and detected door open in an area with only one entrance that is controlled with the door sensor.
  domain: automation
  input:
    area_state:
      name: Area state
      selector:
        entity:
          domain: input_select
    not_occupied_closed_action:
      name: Not occupied closed
      description: Action to execute when the room is not occupied and the door is closed. For example turn off the lights
      default: []
      selector:
        action: {}
    not_occupied_open_action:
      name: Not occupied open
      description: Action to execute when the room is not occupied and the door is open. For example turn off the lights
      default: []
      selector:
        action: {}
    occupied_closed_action:
      name: Occupied closed
      description: Action to execute when the room is occupied and the door is closed. For example turn on the lights
      default: []
      selector:
        action: {}
    occupied_open_action:
      name: Occupied open
      description: Action to execute when the room is occupied and the door is open. For example turn on the lights
      default: []
      selector:
        action: {}
    checking_entry_action:
      name: Checking entry
      description: When the room was not occupied and the door closed if the door opens we must check if it is an entry o not. For example turn on the lights
      default: []
      selector:
        action: {}
    checking_occupancy_by_closure_action:
      name: Checking occupancy by closure
      description: When the room was occupied and the door open if the door closes we must check if it is an exit o not. For example turn on the lights
      default: []
      selector:
        action: {}
    checking_occupancy_by_opening_action:
      name: Checking occupancy by opening
      description: When the room was occupied and the door closed if the door opens we must check if it is an exit o not. For example turn on the lights
      default: []
      selector:
        action: {}
mode: parallel
trigger:
  - platform: state
    entity_id: !input "area_state"
action:
  - variables:
      area_input_select: !input "area_state"
  - choose:
      - conditions:
          - condition: state
            entity_id: !input "area_state"
            state: Not occupied and closed
        sequence: !input "not_occupied_closed_action"
      - conditions:
          - condition: state
            entity_id: !input "area_state"
            state: Checking entry
        sequence: !input "checking_entry_action"
      - conditions:
          - condition: state
            entity_id: !input "area_state"
            state: Not occupied and open
        sequence: !input "not_occupied_open_action"
      - conditions:
          - condition: state
            entity_id: !input "area_state"
            state: Occupied and closed
        sequence: !input "occupied_open_action"
      - conditions:
          - condition: state
            entity_id: !input "area_state"
            state: Checking occupancy by closure
        sequence: !input "checking_occupancy_by_closure_action"
      - conditions:
          - condition: state
            entity_id: !input "area_state"
            state: Checking occupancy by opening
        sequence: !input "checking_occupancy_by_opening_action"
      - conditions:
          - condition: state
            entity_id: !input "area_state"
            state: Occupied and closed
        sequence: !input "occupied_closed_action"
