blueprint:
  name: LPB - Query response
  description: '
  
  This blueprint responds to querys of the state of the room.

  '
  domain: automation
  input:
    area_state:
      name: Area state
      description: 'Input select that handles the area state.'
      selector:
        entity:
          domain: input_select
mode: parallel
trigger:
  - platform: event
    event_type: less_push_buttons
    event_data:
      lpb_type: query
      query_state: Occupied
condition:
  - condition: state
    entity_id: !input "area_state"
    state:
      - Occupied and closed
      - Occupied and open
      - Occupied
action:
  - event: less_push_buttons
    event_data:
      lpb_type: response
      occupied: true
      target_entity_id: "{{ trigger.event.data.origin_entity_id }}"
      origin_entity_id: !input "area_state"
      origin_state: Query
      