blueprint:
  name: LPB - Wellness of room ventilation with a door/window sensor
  description: '
  
  This blueprint controls the ventilation of one room with a door/window sensor.

  It also notifies occupancy of the room in the Less Push Button ecosystem.

  '
  domain: automation
  input:
    door_sensor:
      name: Window Sensor
      description: The window sensor of the room.
      selector:
        entity:
          domain: binary_sensor
          device_class: opening
    outdoor_temperature_sensor:
      name: Outdoor temperature Sensor
      description: The outdoor temperature sensor.
      selector:
        entity:
          domain: sensor
          device_class: temperature
    indoor_temperature_sensor:
      name: Indoor temperature Sensor
      description: The iutdoor temperature sensor.
      selector:
        entity:
          domain: sensor
          device_class: temperature
    temperature_limit:
      name: Temperature limit
      description: Diference between outdoor an indoor temperature to trigger the actions.
      default: 10
      selector:
        number:
          min: 1.0
          max: 50.0
          mode: slider
          step: 0.5
    area_state:
      name: Area state
      description: 'Input select that handles the area state.'
      selector:
        entity:
          domain: input_select
    closed_wait:
      name: Maximum time
      description: Maximum time with the door/window open if the temperature limit is exceed.
      default: 60
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    temperature_exceeded_action:
      name: Temperature limit exceeded actions
      description: Action to execute when the time and the temperature are exceed
      default: []
      selector:
        action: {}
mode: parallel
trigger:
  - platform: state
    entity_id: !input "door_sensor"  
action:
  - variables:
      door_entity_id: !input "door_sensor"
      outdoor_temperature_sensor_id: !input "outdoor_temperature_sensor"
      indoor_temperature_sensor_id: !input "indoor_temperature_sensor"
      temperature_limit_var: !input "temperature_limit"
      door_open: "{{ trigger.entity_id == door_entity_id and trigger.to_state.state == 'on' }}"
      temperature_limit_exceeded: "{{ ((states(outdoor_temperature_sensor_id) | float) - ( states(indoor_temperature_sensor_id) | float )) | abs > (temperature_limit_var | float)}}"
# Less push event
  - event: less_push_buttons
    event_data:
      lpb_type: notify
      occupied: true
      target_entity_id: !input "area_state"
      origin_entity_id: !input "area_state"
      origin_state: External
# Events and next state
  - choose:
      - conditions:
          - "{{ door_open }}"
          - "{{ temperature_limit_exceeded }}"
        sequence:
          - wait_template: "{{ is_state(door_entity_id, 'off') }}"
            timeout: !input "closed_wait"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ not wait.completed }}"
                sequence: !input "temperature_exceeded_action"
