blueprint:
  name: LPB - Only one entrace room occupancy state controlled by a door sensor and a occupancy sensor
  description: 'This blueprint controls the occupancy of one room with only one entrance using one door sensor and a occupancy sensor.

  The state of the room is maintained in an input select, that must exists, with the following items:
      - Occupied
      - Not occupied
      - Possible exit
      - Checking occupancy

  It also checks the rest of the Less Push Buttons ecosystem of automations to complement the occupancy sensor.
  '
  domain: automation
  input:
    occupancy_sensor:
      name: Occupancy Sensor
      description: XThis sensor will be synchronized with the light.
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy
    door_sensor:
      name: Door Sensor
      description: XThis sensor will be synchronized with the light.
      selector:
        entity:
          domain: binary_sensor
          device_class: opening
    area_state:
      name: Area state
      description: 'Input select that handles the area state. It must have the following items:
      - Occupied
      - Not occupied
      - Possible exit
      - Checking occupancy
      '
      selector:
        entity:
          domain: input_select
mode: parallel
trigger:
  - platform: state
    entity_id: !input "door_sensor"
  - platform: event
    event_type: less_push_buttons
    event_data:
      target_entity_id: !input "area_state"
  - platform: state
    entity_id: !input "area_state"
action:
  - variables:
      occupancy_sensor_id: !input "occupancy_sensor"
      door_entity_id: !input "door_sensor"
      door_open: "{{ trigger.entity_id == door_entity_id and trigger.to_state.state == 'on' }}"
      door_closed: "{{ trigger.entity_id == door_entity_id and trigger.to_state.state == 'off' }}"
      area_input_select: !input "area_state"
  - choose:
      - conditions:
          - "{{ door_open }}"
          - "{{ is_state(area_input_select, 'Vacio y cerrada') }}"
        sequence:
          - service: input_select.select_option
            data:
              entity_id: !input "area_state"
              option: Posible entrada
      - conditions:
          - "{{ door_open }}"
          - "{{ is_state(area_input_select, 'Ocupado y cerrada') }}"
        sequence:
          - service: input_select.select_option
            data:
              entity_id: !input "area_state"
              option: Posible salida 2
      - conditions:
          - "{{ door_closed }}"
          - "{{ is_state(area_input_select, 'Posible entrada') }}"
        sequence:
          - service: input_select.select_option
            data:
              entity_id: !input "area_state"
              option: Vacio y cerrada
      - conditions:
          - "{{ door_closed }}"
          - "{{ is_state(area_input_select, 'Vacio y abierta') }}"
        sequence:
          - service: input_select.select_option
            data:
              entity_id: !input "area_state"
              option: Vacio y cerrada
      - conditions:
          - "{{ door_closed }}"
          - "{{ is_state(area_input_select, 'Ocupado y abierta') }}"
        sequence:
          - service: input_select.select_option
            data:
              entity_id: !input "area_state"
              option: Posible salida 1
      - conditions:
          - "{{ door_closed }}"
          - "{{ is_state(area_input_select, 'Posible salida 2') }}"
        sequence:
          - service: input_select.select_option
            data:
              entity_id: !input "area_state"
              option: Vacio y cerrada
      - conditions:
          - "{{ trigger.event.data.occupied == true }}"
          - "{{ is_state(area_input_select, 'Vacio y cerrada') or is_state(area_input_select, 'Posible salida 1') }}"
          - "{{ is_state(area_input_select, trigger.event.data.origin_state) and trigger.event.data.origin_entity_id == area_input_select }}"
        sequence:
          - service: input_select.select_option
            data:
              entity_id: !input "area_state"
              option: Ocupado y cerrada
      - conditions:
          - "{{ trigger.event.data.occupied == true }}"
          - "{{ is_state(area_input_select, 'Posible entrada') or is_state(area_input_select, 'Vacio y abierta') or is_state(area_input_select, 'Ocupado y abierta') or is_state(area_input_select, 'Posible salida 2') }}"
          - "{{ is_state(area_input_select, trigger.event.data.origin_state) and trigger.event.data.origin_entity_id == area_input_select }}"
        sequence:
          - service: input_select.select_option
            data:
              entity_id: !input "area_state"
              option: Ocupado y abierta
      - conditions:
          - "{{ trigger.event.data.occupied == false }}"
          - "{{ is_state(area_input_select, 'Posible entrada') or is_state(area_input_select, 'Ocupado y abierta') or is_state(area_input_select, 'Posible salida 2') }}"
          - "{{ is_state(area_input_select, trigger.event.data.origin_state) and trigger.event.data.origin_entity_id == area_input_select }}"
        sequence:
          - service: input_select.select_option
            data:
              entity_id: !input "area_state"
              option: Vacio y abierta
      - conditions:
          - "{{ trigger.event.data.occupied == false }}"
          - "{{ is_state(area_input_select, 'Posible salida 1') }}"
          - "{{ is_state(area_input_select, trigger.event.data.origin_state) and trigger.event.data.origin_entity_id == area_input_select }}"
        sequence:
          - service: input_select.select_option
            data:
              entity_id: !input "area_state"
              option: Vacio y cerrada
      - conditions:
          - condition: state
            entity_id: !input "area_state"
            state: Vacio y cerrada
        sequence:
          - wait_template: "{{ is_state(occupancy_sensor_id, 'on') }}"
            timeout: "00:00:15"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ wait.completed }}"
                sequence:
                  - event: less_push_buttons
                    event_data:
                      occupied: true
                      target_entity_id: !input "area_state"
                      origin_entity_id: !input "area_state"
                      origin_state: Vacio y cerrada
      - conditions:
          - condition: state
            entity_id: !input "area_state"
            state: Posible entrada
        sequence:
          - wait_template: "{{ is_state(occupancy_sensor_id, 'on') }}"
            timeout: "00:00:15"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ not wait.completed }}"
                sequence:
                  - event: less_push_buttons
                    event_data:
                      occupied: false
                      target_entity_id: !input "area_state"
                      origin_entity_id: !input "area_state"
                      origin_state: Posible entrada
            default:
              - event: less_push_buttons
                event_data:
                  occupied: true
                  target_entity_id: !input "area_state"
                  origin_entity_id: !input "area_state"
                  origin_state: Posible entrada
      - conditions:
          - condition: state
            entity_id: !input "area_state"
            state: Vacio y abierta
        sequence:
          - wait_template: "{{ is_state(occupancy_sensor_id, 'on') }}"
            timeout: 00:00:15
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ wait.completed }}"
                sequence:
                  - event: less_push_buttons
                    event_data:
                      occupied: true
                      target_entity_id: !input "area_state"
                      origin_entity_id: !input "area_state"
                      origin_state: Vacio y abierta
      - conditions:
          - condition: state
            entity_id: !input "area_state"
            state: Ocupado y abierta
        sequence:
          - wait_for_trigger:
              - platform: state
                entity_id: !input occupancy_sensor
                to: "off"
                for: 60
          - event: less_push_buttons
            event_data:
              occupied: false
              target_entity_id: !input "area_state"
              origin_entity_id: !input "area_state"
              origin_state: Ocupado y abierta
      - conditions:
          - condition: state
            entity_id: !input "area_state"
            state: Posible salida 1
        sequence:
          - wait_template: "{{ is_state(occupancy_sensor_id, 'off') }}"
            timeout: "00:00:15"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ not wait.completed }}"
                sequence:
                  - event: less_push_buttons
                    event_data:
                      occupied: true
                      target_entity_id: !input "area_state"
                      origin_entity_id: !input "area_state"
                      origin_state: Posible salida 1
            default:
              - event: less_push_buttons
                event_data:
                  occupied: false
                  target_entity_id: !input "area_state"
                  origin_entity_id: !input "area_state"
                  origin_state: Posible salida 1
      - conditions:
          - condition: state
            entity_id: !input "area_state"
            state: Posible salida 2
        sequence:
          - wait_template: "{{ is_state(occupancy_sensor_id, 'on') }}"
            timeout: "00:00:15"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ not wait.completed }}"
                sequence:
                  - event: less_push_buttons
                    event_data:
                      occupied: false
                      target_entity_id: !input "area_state"
                      origin_entity_id: !input "area_state"
                      origin_state: Posible salida 2
            default:
              - event: less_push_buttons
                event_data:
                  occupied: true
                  target_entity_id: !input "area_state"
                  origin_entity_id: !input "area_state"
                  origin_state: Posible salida 2

